// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by SoftDreams Developer
// **************************************************************************
// ignore_for_file: constant_identifier_names, non_constant_identifier_names

class Assets {
  const Assets._();
  static const String package = 'ekyc';

  static bool isFromModules = false;

  /// {@macro assets_generator.ASSETS_IMAGES_BACKGROUND_LOGIN_BACKGROUND_PNG.preview}
  static String get ASSETS_IMAGES_BACKGROUND_LOGIN_BACKGROUND_PNG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/background/login_background.png';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_PNG_BACKGROUND_BUTTON_NUMBER_WHITE_PNG.preview}
  static String
      get ASSETS_IMAGES_ICON_ICON_PNG_BACKGROUND_BUTTON_NUMBER_WHITE_PNG =>
          '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_png/background_button_number_white.png';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_PNG_IC_INSTRUCT_NUMBER1_PNG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_PNG_IC_INSTRUCT_NUMBER1_PNG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_png/ic_instruct_number1.png';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_PNG_IC_INSTRUCT_NUMBER2_PNG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_PNG_IC_INSTRUCT_NUMBER2_PNG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_png/ic_instruct_number2.png';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_PNG_IC_INSTRUCT_NUMBER2_CTS_PNG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_PNG_IC_INSTRUCT_NUMBER2_CTS_PNG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_png/ic_instruct_number2_cts.png';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_PNG_IC_INSTRUCT_NUMBER3_PNG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_PNG_IC_INSTRUCT_NUMBER3_PNG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_png/ic_instruct_number3.png';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_PNG_ICON_CORNER_LEFT_DOWN_PNG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_PNG_ICON_CORNER_LEFT_DOWN_PNG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_png/icon_corner_left_down.png';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_PNG_ICON_CORNER_LEFT_UP_PNG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_PNG_ICON_CORNER_LEFT_UP_PNG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_png/icon_corner_left_up.png';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_PNG_ICON_CORNER_RIGHT_DOWN_PNG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_PNG_ICON_CORNER_RIGHT_DOWN_PNG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_png/icon_corner_right_down.png';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_PNG_ICON_CORNER_RIGHT_UP_PNG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_PNG_ICON_CORNER_RIGHT_UP_PNG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_png/icon_corner_right_up.png';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_PNG_ICON_FACEID_PNG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_PNG_ICON_FACEID_PNG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_png/icon_faceid.png';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_PNG_IMAGE_DEFAULT_JPG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_PNG_IMAGE_DEFAULT_JPG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_png/image_default.jpg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_PNG_IMG_ACCOUNT_PNG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_PNG_IMG_ACCOUNT_PNG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_png/img_account.png';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_PNG_IMG_BANNER_NFC_PNG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_PNG_IMG_BANNER_NFC_PNG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_png/img_banner_nfc.png';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_PNG_IMG_STOP_QR_PNG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_PNG_IMG_STOP_QR_PNG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_png/img_stop_qr.png';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ERROR_SVGREPO_COM_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ERROR_SVGREPO_COM_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/error-svgrepo-com.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_2ID_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_IC_2ID_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/ic_2id.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_ADD_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_IC_ADD_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/ic_add.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_ADD_IMAGE_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_IC_ADD_IMAGE_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/ic_add_image.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_ADD_ITEM_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_IC_ADD_ITEM_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/ic_add_item.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_ADD_PERSON_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_IC_ADD_PERSON_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/ic_add_person.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_ADD_SIGN_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_IC_ADD_SIGN_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/ic_add_sign.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_ADD_TAKE_PICTURE_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_IC_ADD_TAKE_PICTURE_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/ic_add_take_picture.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_ADDRESS_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_IC_ADDRESS_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/ic_address.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_ATTACHMENT_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_IC_ATTACHMENT_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/ic_attachment.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_ATTACHMENT_EMPTY_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_IC_ATTACHMENT_EMPTY_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/ic_attachment_empty.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_AUTHORITY_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_IC_AUTHORITY_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/ic_authority.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_BANNER_RESET_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_IC_BANNER_RESET_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/ic_banner_reset.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_BANNER_RESET_EMAIL_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_IC_BANNER_RESET_EMAIL_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/ic_banner_reset_email.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_BANNER_SIGN_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_IC_BANNER_SIGN_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/ic_banner_sign.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_BORDER_PICTURE_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_IC_BORDER_PICTURE_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/ic_border_picture.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_CART_CTS_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_IC_CART_CTS_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/ic_cart_cts.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_CART_CTS_BUTTON_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_IC_CART_CTS_BUTTON_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/ic_cart_cts_button.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_CHANGE_PASSWORD_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_IC_CHANGE_PASSWORD_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/ic_change_password.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_CHANGEPASS_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_IC_CHANGEPASS_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/ic_changepass.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_COMPANY_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_IC_COMPANY_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/ic_company.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_DATE_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_IC_DATE_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/ic_date.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_EMAIL_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_IC_EMAIL_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/ic_email.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_EMPTY_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_IC_EMPTY_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/ic_empty.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_EMPTY_SIGN_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_IC_EMPTY_SIGN_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/ic_empty_sign.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_ERROR_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_IC_ERROR_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/ic_error.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_ERROR_SNACKBAR_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_IC_ERROR_SNACKBAR_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/ic_error_snackbar.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_FACEID_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_IC_FACEID_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/ic_faceid.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_FILTER_ACTIVE_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_IC_FILTER_ACTIVE_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/ic_filter_active.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_FINGERPRINT_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_IC_FINGERPRINT_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/ic_fingerprint.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_INFO_SIGN_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_IC_INFO_SIGN_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/ic_info_sign.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_INFO_SIGN_DETAIL_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_IC_INFO_SIGN_DETAIL_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/ic_info_sign_detail.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_INSTRUCT_NEXT_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_IC_INSTRUCT_NEXT_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/ic_instruct_next.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_JOB_ALL_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_IC_JOB_ALL_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/ic_job_all.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_KY_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_IC_KY_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/ic_ky.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_LOGO_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_IC_LOGO_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/ic_logo.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_LOGOUT_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_IC_LOGOUT_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/ic_logout.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_MENU_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_IC_MENU_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/ic_menu.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_MESSAGE_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_IC_MESSAGE_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/ic_message.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_MESSAGE_EMPTY_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_IC_MESSAGE_EMPTY_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/ic_message_empty.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_MORE_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_IC_MORE_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/ic_more.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_NEXT_PAGE_ENABEL_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_IC_NEXT_PAGE_ENABEL_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/ic_next_page_enabel.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_NOTIFICATION_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_IC_NOTIFICATION_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/ic_notification.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_OVERDUE_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_IC_OVERDUE_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/ic_overdue.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_OVERVIEW_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_IC_OVERVIEW_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/ic_overview.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_PASS_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_IC_PASS_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/ic_pass.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_PHONE_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_IC_PHONE_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/ic_phone.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_POSITION_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_IC_POSITION_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/ic_position.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_PREVIOUS_PAGE_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_IC_PREVIOUS_PAGE_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/ic_previous_page.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_PREVIOUS_PAGE_ENABEL_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_IC_PREVIOUS_PAGE_ENABEL_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/ic_previous_page_enabel.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_PROCESSED_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_IC_PROCESSED_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/ic_processed.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_REMOVE_INFO_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_IC_REMOVE_INFO_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/ic_remove_info.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_SETUP_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_IC_SETUP_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/ic_setup.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_SHOW_MENU_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_IC_SHOW_MENU_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/ic_show_menu.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_SIGN_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_IC_SIGN_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/ic_sign.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_SUCCESS_SNACKBAR_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_IC_SUCCESS_SNACKBAR_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/ic_success_snackbar.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_SUPPORT_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_IC_SUPPORT_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/ic_support.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_SUPPORT_BANNER_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_IC_SUPPORT_BANNER_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/ic_support_banner.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_SUPPORT_EMAIL_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_IC_SUPPORT_EMAIL_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/ic_support_email.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_SUPPORT_HOME_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_IC_SUPPORT_HOME_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/ic_support_home.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_SUPPORT_LOCATION_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_IC_SUPPORT_LOCATION_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/ic_support_location.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_SUPPORT_PHONE_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_IC_SUPPORT_PHONE_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/ic_support_phone.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_SUPPORT_WEB_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_IC_SUPPORT_WEB_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/ic_support_web.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_UNPROCESSED_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_IC_UNPROCESSED_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/ic_unprocessed.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_USERNAME_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_IC_USERNAME_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/ic_username.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_VIEW_PDF_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_IC_VIEW_PDF_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/ic_view_pdf.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_WARNING_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_IC_WARNING_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/ic_warning.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_ADD_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_ADD_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_add.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_BACK_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_BACK_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_back.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_BACKWARD_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_BACKWARD_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_backward.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_BOLD_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_BOLD_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_bold.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_CANCEL_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_CANCEL_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_cancel.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_CANCEL_AUTHENTICATION_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_CANCEL_AUTHENTICATION_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_cancel_authentication.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_CAPTURES_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_CAPTURES_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_captures.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_CHECKBOX_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_CHECKBOX_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_checkbox.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_CHECKBOX_EMPTY_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_CHECKBOX_EMPTY_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_checkbox_empty.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_CHECKBOX_TICK_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_CHECKBOX_TICK_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_checkbox_tick.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_CHOOSE_STYLE_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_CHOOSE_STYLE_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_choose_style.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_CLEAR_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_CLEAR_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_clear.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_COMPLETE_SENT_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_COMPLETE_SENT_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_complete_sent.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_DETAILS_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_DETAILS_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_details.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_DETAILS_SELECT_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_DETAILS_SELECT_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_details_select.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_DIGI_CERT_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_DIGI_CERT_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_digi_cert.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_DOC_ICON_DOC_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_DOC_ICON_DOC_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_doc/icon_doc.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_DOC_ICON_DOC_COMPLETE_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_DOC_ICON_DOC_COMPLETE_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_doc/icon_doc_complete.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_DOC_ICON_DOC_OVERDU_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_DOC_ICON_DOC_OVERDU_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_doc/icon_doc_overdu.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_DOC_ICON_DOC_PROCESS_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_DOC_ICON_DOC_PROCESS_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_doc/icon_doc_process.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_DOC_ICON_DOC_REFUSE_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_DOC_ICON_DOC_REFUSE_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_doc/icon_doc_refuse.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_DOC_ICON_FILE_ATTACHED_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_DOC_ICON_FILE_ATTACHED_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_doc/icon_file_attached.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_DOCS_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_DOCS_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_docs.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_DOCS_BLACK_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_DOCS_BLACK_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_docs_black.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_DOCS_DELETED_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_DOCS_DELETED_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_docs_deleted.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_DOCS_DELETED_BLACK_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_DOCS_DELETED_BLACK_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_docs_deleted_black.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_DOCS_DRAFT_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_DOCS_DRAFT_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_docs_draft.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_DOCS_DRAFT_BLACK_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_DOCS_DRAFT_BLACK_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_docs_draft_black.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_DOCS_SENT_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_DOCS_SENT_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_docs_sent.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_DOCS_SENT_BLACK_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_DOCS_SENT_BLACK_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_docs_sent_black.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_DOCUMENT_WORD_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_DOCUMENT_WORD_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_document_word.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_DONE_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_DONE_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_done.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_DOWNLOAD_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_DOWNLOAD_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_download.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_DRAW_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_DRAW_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_draw.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_EDIT_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_EDIT_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_edit.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_EDIT_PEN_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_EDIT_PEN_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_edit_pen.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_ELLIPSE_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_ELLIPSE_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_ellipse.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_EYE_OFF_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_EYE_OFF_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_eye_off.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_EYE_ON_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_EYE_ON_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_eye_on.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_FACE_BETWEEN_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_FACE_BETWEEN_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_face_between.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_FACE_BLINK_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_FACE_BLINK_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_face_blink.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_FACE_DOWN_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_FACE_DOWN_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_face_down.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_FACE_LEFT_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_FACE_LEFT_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_face_left.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_FACE_RIGHT_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_FACE_RIGHT_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_face_right.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_FACE_SMILE_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_FACE_SMILE_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_face_smile.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_FACE_UP_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_FACE_UP_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_face_up.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_FILTER_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_FILTER_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_filter.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_FLASH_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_FLASH_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_flash.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_FLASH_OFF_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_FLASH_OFF_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_flash_off.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_FORDWARD_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_FORDWARD_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_fordward.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_HOME_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_HOME_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_home.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_HOME_SELECT_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_HOME_SELECT_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_home_select.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_IMAGE_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_IMAGE_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_image.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_INFORMATION_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_INFORMATION_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_information.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_ITALIC_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_ITALIC_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_italic.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_KYC_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_KYC_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_kyc.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_LOGO_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_LOGO_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_logo.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_LOGOUT_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_LOGOUT_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_logout.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_MARK_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_MARK_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_mark.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_MENU_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_MENU_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_menu.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_MENU_ADD_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_MENU_ADD_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_menu_add.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_MORE_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_MORE_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_more.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_NO_SUPPORT_NFC_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_NO_SUPPORT_NFC_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_no_support_nfc.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_NOTI_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_NOTI_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_noti.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_NOTIFICATION_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_NOTIFICATION_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_notification.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_PAGE_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_PAGE_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_page.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_PDF_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_PDF_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_pdf.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_PEN_WRITING_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_PEN_WRITING_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_pen_writing.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_PROFILE_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_PROFILE_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_profile.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_PROFILE_SELECT_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_PROFILE_SELECT_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_profile_select.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_RED_CANCEL_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_RED_CANCEL_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_red_cancel.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_REJECT_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_REJECT_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_reject.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_SAVE_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_SAVE_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_save.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_SCAN_NFC_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_SCAN_NFC_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_scan_nfc.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_SEARCH_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_SEARCH_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_search.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_SECURITY_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_SECURITY_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_security.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_SEE_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_SEE_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_see.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_SENT_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_SENT_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_sent.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_SHARE_DOCUMENT_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_SHARE_DOCUMENT_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_share_document.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_SUPPORT_NFC_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_SUPPORT_NFC_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_support_nfc.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_TIME_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_TIME_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_time.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_TRASH_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_TRASH_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_trash.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_UP_IMAGE_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_UP_IMAGE_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_up_image.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_UPLOAD_IMAGE_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_UPLOAD_IMAGE_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_upload_image.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_VIEW_PDF_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_VIEW_PDF_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_view_pdf.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_WARNING_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_ICON_WARNING_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/icon_warning.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IXEX_NEXT_PAGE_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_IXEX_NEXT_PAGE_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/ixex_next_page.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_NOTIFICATION_13_SVGREPO_COM_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_NOTIFICATION_13_SVGREPO_COM_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/notification-13-svgrepo-com.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_SUCCESS_STANDARD_SVGREPO_COM_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_SUCCESS_STANDARD_SVGREPO_COM_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/success-standard-svgrepo-com.svg';

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_WARNING_SVGREPO_COM_SVG.preview}
  static String get ASSETS_IMAGES_ICON_ICON_SVG_WARNING_SVGREPO_COM_SVG =>
      '${isFromModules ? "packages/$package/" : ""}assets/images/icon/icon_svg/warning-svgrepo-com.svg';
}

final List<String> assetsArray = <String>[
  /// {@macro assets_generator.ASSETS_IMAGES_BACKGROUND_LOGIN_BACKGROUND_PNG.preview}
  Assets.ASSETS_IMAGES_BACKGROUND_LOGIN_BACKGROUND_PNG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_PNG_BACKGROUND_BUTTON_NUMBER_WHITE_PNG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_PNG_BACKGROUND_BUTTON_NUMBER_WHITE_PNG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_PNG_IC_INSTRUCT_NUMBER1_PNG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_PNG_IC_INSTRUCT_NUMBER1_PNG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_PNG_IC_INSTRUCT_NUMBER2_PNG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_PNG_IC_INSTRUCT_NUMBER2_PNG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_PNG_IC_INSTRUCT_NUMBER2_CTS_PNG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_PNG_IC_INSTRUCT_NUMBER2_CTS_PNG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_PNG_IC_INSTRUCT_NUMBER3_PNG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_PNG_IC_INSTRUCT_NUMBER3_PNG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_PNG_ICON_CORNER_LEFT_DOWN_PNG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_PNG_ICON_CORNER_LEFT_DOWN_PNG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_PNG_ICON_CORNER_LEFT_UP_PNG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_PNG_ICON_CORNER_LEFT_UP_PNG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_PNG_ICON_CORNER_RIGHT_DOWN_PNG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_PNG_ICON_CORNER_RIGHT_DOWN_PNG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_PNG_ICON_CORNER_RIGHT_UP_PNG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_PNG_ICON_CORNER_RIGHT_UP_PNG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_PNG_ICON_FACEID_PNG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_PNG_ICON_FACEID_PNG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_PNG_IMAGE_DEFAULT_JPG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_PNG_IMAGE_DEFAULT_JPG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_PNG_IMG_ACCOUNT_PNG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_PNG_IMG_ACCOUNT_PNG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_PNG_IMG_BANNER_NFC_PNG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_PNG_IMG_BANNER_NFC_PNG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_PNG_IMG_STOP_QR_PNG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_PNG_IMG_STOP_QR_PNG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ERROR_SVGREPO_COM_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_ERROR_SVGREPO_COM_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_2ID_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_IC_2ID_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_ADD_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_IC_ADD_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_ADD_IMAGE_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_IC_ADD_IMAGE_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_ADD_ITEM_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_IC_ADD_ITEM_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_ADD_PERSON_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_IC_ADD_PERSON_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_ADD_SIGN_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_IC_ADD_SIGN_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_ADD_TAKE_PICTURE_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_IC_ADD_TAKE_PICTURE_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_ADDRESS_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_IC_ADDRESS_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_ATTACHMENT_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_IC_ATTACHMENT_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_ATTACHMENT_EMPTY_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_IC_ATTACHMENT_EMPTY_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_AUTHORITY_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_IC_AUTHORITY_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_BANNER_RESET_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_IC_BANNER_RESET_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_BANNER_RESET_EMAIL_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_IC_BANNER_RESET_EMAIL_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_BANNER_SIGN_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_IC_BANNER_SIGN_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_BORDER_PICTURE_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_IC_BORDER_PICTURE_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_CART_CTS_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_IC_CART_CTS_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_CART_CTS_BUTTON_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_IC_CART_CTS_BUTTON_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_CHANGE_PASSWORD_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_IC_CHANGE_PASSWORD_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_CHANGEPASS_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_IC_CHANGEPASS_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_COMPANY_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_IC_COMPANY_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_DATE_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_IC_DATE_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_EMAIL_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_IC_EMAIL_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_EMPTY_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_IC_EMPTY_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_EMPTY_SIGN_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_IC_EMPTY_SIGN_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_ERROR_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_IC_ERROR_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_ERROR_SNACKBAR_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_IC_ERROR_SNACKBAR_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_FACEID_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_IC_FACEID_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_FILTER_ACTIVE_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_IC_FILTER_ACTIVE_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_FINGERPRINT_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_IC_FINGERPRINT_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_INFO_SIGN_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_IC_INFO_SIGN_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_INFO_SIGN_DETAIL_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_IC_INFO_SIGN_DETAIL_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_INSTRUCT_NEXT_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_IC_INSTRUCT_NEXT_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_JOB_ALL_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_IC_JOB_ALL_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_KY_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_IC_KY_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_LOGO_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_IC_LOGO_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_LOGOUT_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_IC_LOGOUT_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_MENU_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_IC_MENU_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_MESSAGE_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_IC_MESSAGE_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_MESSAGE_EMPTY_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_IC_MESSAGE_EMPTY_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_MORE_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_IC_MORE_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_NEXT_PAGE_ENABEL_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_IC_NEXT_PAGE_ENABEL_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_NOTIFICATION_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_IC_NOTIFICATION_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_OVERDUE_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_IC_OVERDUE_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_OVERVIEW_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_IC_OVERVIEW_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_PASS_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_IC_PASS_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_PHONE_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_IC_PHONE_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_POSITION_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_IC_POSITION_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_PREVIOUS_PAGE_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_IC_PREVIOUS_PAGE_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_PREVIOUS_PAGE_ENABEL_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_IC_PREVIOUS_PAGE_ENABEL_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_PROCESSED_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_IC_PROCESSED_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_REMOVE_INFO_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_IC_REMOVE_INFO_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_SETUP_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_IC_SETUP_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_SHOW_MENU_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_IC_SHOW_MENU_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_SIGN_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_IC_SIGN_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_SUCCESS_SNACKBAR_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_IC_SUCCESS_SNACKBAR_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_SUPPORT_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_IC_SUPPORT_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_SUPPORT_BANNER_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_IC_SUPPORT_BANNER_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_SUPPORT_EMAIL_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_IC_SUPPORT_EMAIL_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_SUPPORT_HOME_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_IC_SUPPORT_HOME_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_SUPPORT_LOCATION_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_IC_SUPPORT_LOCATION_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_SUPPORT_PHONE_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_IC_SUPPORT_PHONE_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_SUPPORT_WEB_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_IC_SUPPORT_WEB_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_UNPROCESSED_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_IC_UNPROCESSED_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_USERNAME_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_IC_USERNAME_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_VIEW_PDF_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_IC_VIEW_PDF_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_WARNING_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_IC_WARNING_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_ADD_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_ICON_ADD_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_BACK_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_ICON_BACK_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_BACKWARD_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_ICON_BACKWARD_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_BOLD_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_ICON_BOLD_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_CANCEL_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_ICON_CANCEL_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_CANCEL_AUTHENTICATION_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_ICON_CANCEL_AUTHENTICATION_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_CAPTURES_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_ICON_CAPTURES_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_CHECKBOX_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_ICON_CHECKBOX_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_CHECKBOX_EMPTY_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_ICON_CHECKBOX_EMPTY_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_CHECKBOX_TICK_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_ICON_CHECKBOX_TICK_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_CHOOSE_STYLE_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_ICON_CHOOSE_STYLE_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_CLEAR_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_ICON_CLEAR_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_COMPLETE_SENT_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_ICON_COMPLETE_SENT_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_DETAILS_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_ICON_DETAILS_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_DETAILS_SELECT_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_ICON_DETAILS_SELECT_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_DIGI_CERT_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_ICON_DIGI_CERT_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_DOC_ICON_DOC_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_ICON_DOC_ICON_DOC_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_DOC_ICON_DOC_COMPLETE_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_ICON_DOC_ICON_DOC_COMPLETE_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_DOC_ICON_DOC_OVERDU_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_ICON_DOC_ICON_DOC_OVERDU_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_DOC_ICON_DOC_PROCESS_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_ICON_DOC_ICON_DOC_PROCESS_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_DOC_ICON_DOC_REFUSE_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_ICON_DOC_ICON_DOC_REFUSE_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_DOC_ICON_FILE_ATTACHED_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_ICON_DOC_ICON_FILE_ATTACHED_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_DOCS_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_ICON_DOCS_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_DOCS_BLACK_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_ICON_DOCS_BLACK_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_DOCS_DELETED_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_ICON_DOCS_DELETED_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_DOCS_DELETED_BLACK_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_ICON_DOCS_DELETED_BLACK_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_DOCS_DRAFT_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_ICON_DOCS_DRAFT_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_DOCS_DRAFT_BLACK_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_ICON_DOCS_DRAFT_BLACK_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_DOCS_SENT_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_ICON_DOCS_SENT_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_DOCS_SENT_BLACK_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_ICON_DOCS_SENT_BLACK_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_DOCUMENT_WORD_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_ICON_DOCUMENT_WORD_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_DONE_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_ICON_DONE_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_DOWNLOAD_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_ICON_DOWNLOAD_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_DRAW_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_ICON_DRAW_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_EDIT_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_ICON_EDIT_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_EDIT_PEN_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_ICON_EDIT_PEN_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_ELLIPSE_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_ICON_ELLIPSE_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_EYE_OFF_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_ICON_EYE_OFF_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_EYE_ON_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_ICON_EYE_ON_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_FACE_BETWEEN_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_ICON_FACE_BETWEEN_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_FACE_BLINK_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_ICON_FACE_BLINK_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_FACE_DOWN_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_ICON_FACE_DOWN_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_FACE_LEFT_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_ICON_FACE_LEFT_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_FACE_RIGHT_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_ICON_FACE_RIGHT_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_FACE_SMILE_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_ICON_FACE_SMILE_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_FACE_UP_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_ICON_FACE_UP_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_FILTER_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_ICON_FILTER_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_FLASH_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_ICON_FLASH_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_FLASH_OFF_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_ICON_FLASH_OFF_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_FORDWARD_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_ICON_FORDWARD_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_HOME_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_ICON_HOME_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_HOME_SELECT_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_ICON_HOME_SELECT_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_IMAGE_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_ICON_IMAGE_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_INFORMATION_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_ICON_INFORMATION_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_ITALIC_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_ICON_ITALIC_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_KYC_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_ICON_KYC_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_LOGO_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_ICON_LOGO_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_LOGOUT_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_ICON_LOGOUT_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_MARK_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_ICON_MARK_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_MENU_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_ICON_MENU_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_MENU_ADD_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_ICON_MENU_ADD_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_MORE_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_ICON_MORE_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_NO_SUPPORT_NFC_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_ICON_NO_SUPPORT_NFC_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_NOTI_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_ICON_NOTI_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_NOTIFICATION_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_ICON_NOTIFICATION_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_PAGE_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_ICON_PAGE_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_PDF_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_ICON_PDF_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_PEN_WRITING_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_ICON_PEN_WRITING_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_PROFILE_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_ICON_PROFILE_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_PROFILE_SELECT_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_ICON_PROFILE_SELECT_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_RED_CANCEL_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_ICON_RED_CANCEL_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_REJECT_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_ICON_REJECT_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_SAVE_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_ICON_SAVE_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_SCAN_NFC_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_ICON_SCAN_NFC_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_SEARCH_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_ICON_SEARCH_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_SECURITY_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_ICON_SECURITY_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_SEE_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_ICON_SEE_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_SENT_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_ICON_SENT_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_SHARE_DOCUMENT_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_ICON_SHARE_DOCUMENT_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_SUPPORT_NFC_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_ICON_SUPPORT_NFC_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_TIME_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_ICON_TIME_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_TRASH_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_ICON_TRASH_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_UP_IMAGE_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_ICON_UP_IMAGE_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_UPLOAD_IMAGE_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_ICON_UPLOAD_IMAGE_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_VIEW_PDF_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_ICON_VIEW_PDF_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_WARNING_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_ICON_WARNING_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IXEX_NEXT_PAGE_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_IXEX_NEXT_PAGE_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_NOTIFICATION_13_SVGREPO_COM_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_NOTIFICATION_13_SVGREPO_COM_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_SUCCESS_STANDARD_SVGREPO_COM_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_SUCCESS_STANDARD_SVGREPO_COM_SVG,

  /// {@macro assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_WARNING_SVGREPO_COM_SVG.preview}
  Assets.ASSETS_IMAGES_ICON_ICON_SVG_WARNING_SVGREPO_COM_SVG,
];
