// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by SoftDreams Developer
// **************************************************************************
// ignore_for_file: constant_identifier_names, non_constant_identifier_names

/// {@template assets_generator.ASSETS_IMAGES_BACKGROUND_LOGIN_BACKGROUND_PNG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/background/login_background.png)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_PNG_BACKGROUND_BUTTON_NUMBER_WHITE_PNG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_png/background_button_number_white.png)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_PNG_IC_INSTRUCT_NUMBER1_PNG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_png/ic_instruct_number1.png)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_PNG_IC_INSTRUCT_NUMBER2_PNG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_png/ic_instruct_number2.png)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_PNG_IC_INSTRUCT_NUMBER2_CTS_PNG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_png/ic_instruct_number2_cts.png)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_PNG_IC_INSTRUCT_NUMBER3_PNG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_png/ic_instruct_number3.png)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_PNG_ICON_CORNER_LEFT_DOWN_PNG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_png/icon_corner_left_down.png)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_PNG_ICON_CORNER_LEFT_UP_PNG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_png/icon_corner_left_up.png)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_PNG_ICON_CORNER_RIGHT_DOWN_PNG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_png/icon_corner_right_down.png)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_PNG_ICON_CORNER_RIGHT_UP_PNG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_png/icon_corner_right_up.png)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_PNG_ICON_FACEID_PNG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_png/icon_faceid.png)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_PNG_IMAGE_DEFAULT_JPG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_png/image_default.jpg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_PNG_IMG_ACCOUNT_PNG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_png/img_account.png)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_PNG_IMG_BANNER_NFC_PNG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_png/img_banner_nfc.png)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_PNG_IMG_STOP_QR_PNG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_png/img_stop_qr.png)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ERROR_SVGREPO_COM_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/error-svgrepo-com.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_2ID_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/ic_2id.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_ADD_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/ic_add.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_ADD_IMAGE_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/ic_add_image.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_ADD_ITEM_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/ic_add_item.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_ADD_PERSON_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/ic_add_person.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_ADD_SIGN_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/ic_add_sign.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_ADD_TAKE_PICTURE_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/ic_add_take_picture.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_ADDRESS_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/ic_address.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_ATTACHMENT_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/ic_attachment.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_ATTACHMENT_EMPTY_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/ic_attachment_empty.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_AUTHORITY_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/ic_authority.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_BANNER_RESET_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/ic_banner_reset.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_BANNER_RESET_EMAIL_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/ic_banner_reset_email.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_BANNER_SIGN_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/ic_banner_sign.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_BORDER_PICTURE_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/ic_border_picture.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_CART_CTS_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/ic_cart_cts.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_CART_CTS_BUTTON_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/ic_cart_cts_button.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_CHANGE_PASSWORD_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/ic_change_password.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_CHANGEPASS_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/ic_changepass.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_COMPANY_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/ic_company.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_DATE_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/ic_date.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_EMAIL_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/ic_email.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_EMPTY_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/ic_empty.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_EMPTY_SIGN_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/ic_empty_sign.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_ERROR_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/ic_error.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_ERROR_SNACKBAR_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/ic_error_snackbar.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_FACEID_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/ic_faceid.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_FILTER_ACTIVE_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/ic_filter_active.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_FINGERPRINT_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/ic_fingerprint.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_INFO_SIGN_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/ic_info_sign.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_INFO_SIGN_DETAIL_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/ic_info_sign_detail.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_INSTRUCT_NEXT_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/ic_instruct_next.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_JOB_ALL_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/ic_job_all.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_KY_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/ic_ky.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_LOGO_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/ic_logo.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_LOGOUT_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/ic_logout.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_MENU_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/ic_menu.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_MESSAGE_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/ic_message.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_MESSAGE_EMPTY_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/ic_message_empty.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_MORE_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/ic_more.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_NEXT_PAGE_ENABEL_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/ic_next_page_enabel.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_NOTIFICATION_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/ic_notification.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_OVERDUE_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/ic_overdue.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_OVERVIEW_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/ic_overview.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_PASS_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/ic_pass.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_PHONE_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/ic_phone.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_POSITION_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/ic_position.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_PREVIOUS_PAGE_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/ic_previous_page.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_PREVIOUS_PAGE_ENABEL_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/ic_previous_page_enabel.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_PROCESSED_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/ic_processed.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_REMOVE_INFO_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/ic_remove_info.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_SETUP_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/ic_setup.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_SHOW_MENU_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/ic_show_menu.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_SIGN_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/ic_sign.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_SUCCESS_SNACKBAR_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/ic_success_snackbar.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_SUPPORT_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/ic_support.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_SUPPORT_BANNER_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/ic_support_banner.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_SUPPORT_EMAIL_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/ic_support_email.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_SUPPORT_HOME_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/ic_support_home.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_SUPPORT_LOCATION_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/ic_support_location.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_SUPPORT_PHONE_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/ic_support_phone.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_SUPPORT_WEB_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/ic_support_web.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_UNPROCESSED_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/ic_unprocessed.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_USERNAME_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/ic_username.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_VIEW_PDF_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/ic_view_pdf.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IC_WARNING_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/ic_warning.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_ADD_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/icon_add.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_BACK_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/icon_back.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_BACKWARD_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/icon_backward.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_BOLD_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/icon_bold.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_CANCEL_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/icon_cancel.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_CANCEL_AUTHENTICATION_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/icon_cancel_authentication.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_CAPTURES_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/icon_captures.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_CHECKBOX_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/icon_checkbox.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_CHECKBOX_EMPTY_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/icon_checkbox_empty.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_CHECKBOX_TICK_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/icon_checkbox_tick.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_CHOOSE_STYLE_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/icon_choose_style.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_CLEAR_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/icon_clear.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_COMPLETE_SENT_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/icon_complete_sent.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_DETAILS_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/icon_details.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_DETAILS_SELECT_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/icon_details_select.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_DIGI_CERT_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/icon_digi_cert.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_DOC_ICON_DOC_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/icon_doc/icon_doc.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_DOC_ICON_DOC_COMPLETE_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/icon_doc/icon_doc_complete.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_DOC_ICON_DOC_OVERDU_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/icon_doc/icon_doc_overdu.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_DOC_ICON_DOC_PROCESS_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/icon_doc/icon_doc_process.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_DOC_ICON_DOC_REFUSE_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/icon_doc/icon_doc_refuse.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_DOC_ICON_FILE_ATTACHED_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/icon_doc/icon_file_attached.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_DOCS_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/icon_docs.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_DOCS_BLACK_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/icon_docs_black.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_DOCS_DELETED_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/icon_docs_deleted.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_DOCS_DELETED_BLACK_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/icon_docs_deleted_black.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_DOCS_DRAFT_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/icon_docs_draft.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_DOCS_DRAFT_BLACK_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/icon_docs_draft_black.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_DOCS_SENT_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/icon_docs_sent.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_DOCS_SENT_BLACK_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/icon_docs_sent_black.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_DOCUMENT_WORD_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/icon_document_word.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_DONE_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/icon_done.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_DOWNLOAD_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/icon_download.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_DRAW_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/icon_draw.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_EDIT_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/icon_edit.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_EDIT_PEN_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/icon_edit_pen.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_ELLIPSE_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/icon_ellipse.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_EYE_OFF_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/icon_eye_off.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_EYE_ON_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/icon_eye_on.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_FACE_BETWEEN_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/icon_face_between.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_FACE_BLINK_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/icon_face_blink.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_FACE_DOWN_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/icon_face_down.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_FACE_LEFT_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/icon_face_left.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_FACE_RIGHT_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/icon_face_right.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_FACE_SMILE_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/icon_face_smile.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_FACE_UP_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/icon_face_up.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_FILTER_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/icon_filter.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_FLASH_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/icon_flash.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_FLASH_OFF_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/icon_flash_off.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_FORDWARD_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/icon_fordward.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_HOME_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/icon_home.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_HOME_SELECT_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/icon_home_select.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_IMAGE_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/icon_image.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_INFORMATION_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/icon_information.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_ITALIC_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/icon_italic.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_KYC_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/icon_kyc.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_LOGO_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/icon_logo.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_LOGOUT_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/icon_logout.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_MARK_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/icon_mark.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_MENU_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/icon_menu.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_MENU_ADD_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/icon_menu_add.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_MORE_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/icon_more.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_NO_SUPPORT_NFC_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/icon_no_support_nfc.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_NOTI_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/icon_noti.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_NOTIFICATION_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/icon_notification.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_PAGE_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/icon_page.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_PDF_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/icon_pdf.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_PEN_WRITING_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/icon_pen_writing.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_PROFILE_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/icon_profile.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_PROFILE_SELECT_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/icon_profile_select.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_RED_CANCEL_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/icon_red_cancel.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_REJECT_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/icon_reject.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_SAVE_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/icon_save.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_SCAN_NFC_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/icon_scan_nfc.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_SEARCH_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/icon_search.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_SECURITY_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/icon_security.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_SEE_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/icon_see.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_SENT_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/icon_sent.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_SHARE_DOCUMENT_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/icon_share_document.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_SUPPORT_NFC_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/icon_support_nfc.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_TIME_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/icon_time.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_TRASH_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/icon_trash.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_UP_IMAGE_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/icon_up_image.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_UPLOAD_IMAGE_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/icon_upload_image.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_VIEW_PDF_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/icon_view_pdf.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_ICON_WARNING_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/icon_warning.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_IXEX_NEXT_PAGE_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/ixex_next_page.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_NOTIFICATION_13_SVGREPO_COM_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/notification-13-svgrepo-com.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_SUCCESS_STANDARD_SVGREPO_COM_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/success-standard-svgrepo-com.svg)
/// {@endtemplate}

/// {@template assets_generator.ASSETS_IMAGES_ICON_ICON_SVG_WARNING_SVGREPO_COM_SVG.preview}
/// ![](d:\lochv\flutter project\2id\ekyc\assets/images/icon/icon_svg/warning-svgrepo-com.svg)
/// {@endtemplate}

// ignore_for_file: camel_case_types, unused_element
class _ {}